### ISSUE TITLE
smart open dev's with unix.O_RDWR and thus crashes with a read-only mount

### ISSUE THREAD

**Issue by nektro** [dswarbrick/smart#1]
To preserve the safety of host devices the app is initialized as such:
```yml
        volumes:
            - .:/app/
            - /:/host:ro
```

Using `:ro` make `SCSIDevice.Open` crash with an `operation not permitted` error.

**Comment by nektro** [comment]
Btw just found this library and love it and am excited to see where you take it :)

**Comment by dswarbrick** [comment]
Hi, thanks for reporting this. Does all functionality work as expected if you change the permissions to `O_RDONLY`? I probably assumed that it would need `O_RDWR` because the code performs ioctl _writes_, but OTOH it's not writing to block device sectors, per se.

**Comment by nektro** [comment]
I'm not sure, haven't yet tested changing the code yet. I found this because if I do `sudo go run main.go` then everything works as expected, but if i use `docker-compose` with `:ro` (which is the eventual env I planned on deploying the app I'm making in) then I ran into the error.

**Comment by dswarbrick** [comment]
I presume you are referring to some code of your own, because there is no main.go in this repo. If you are referring to smartctl.go, you should take note of the `checkCaps` function. Due to the ioctls involved, this library requires `CAP_SYS_RAWIO` and `CAP_SYS_ADMIN` (which root receives).

Since you need to execute it with those capabilities (or as root), changing `unix.Open` to open the device with `O_RDONLY` doesn't really have much effect (and still works), other than guarding against accidentally writing to the block device (e.g., via an unintentional bug).

**Comment by nektro** [comment]
```yml
version: "3"
services:
    app:
        image: golang
        volumes:
            - .:/app/
            - /:/host:ro
        working_dir: /app/
        command: go run main.go
        pid: host
        network_mode: host
        ports:
            - "9095"
        environment:
            ROOT: /host/
```

this is the full config I'm using. the `pid: host` and `network_mode: host` as well as the `/` volume mount give it full access to the system. https://github.com/AnalogJ/scrutiny is another project that does SMART analysis from within a docker process.

the reason for the app I'm making is to be able to not use `scrutiny` but instead make a custom collector for https://prometheus.io/ that I can then feed into https://grafana.com/.
